# See full list of defaults here: https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable

# Layout checks are defined here
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines

Layout/ConditionPosition:
  Enabled: true

Layout/AccessModifierIndentation:
  IndentationWidth: 2

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: no_empty_lines

# Lint checks are defined here
Lint:
  Severity: error

Lint/AmbiguousBlockAssociation:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/SuppressedException:
  Enabled: false

Lint/Loop:
  Enabled: true

# Style checks are defined here
Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/AutoResourceCleanup:
  Enabled: true

Style/WordArray:
  EnforcedStyle: brackets

Style/For:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/AsciiComments:
  Enabled: false

Style/GuardClause:
  Enabled: false

# Metrics like method length and complexity are defined here
Layout/LineLength:
  Max: 250
  IgnoredPatterns: ['\ADado', '\AQuando', '\AEntão', 'identificator']

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 40

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 500

Metrics/AbcSize:
  Max: 100

Metrics/ModuleLength:
  Max: 500

Metrics/BlockLength:
  Max: 50

Metrics/PerceivedComplexity:
  Enabled: false

# Naming like name files are defined here
Naming/FileName:
  Exclude: [Gemfile]

Naming/AccessorMethodName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/VariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Lint/Debugger:
  Enabled: false

Naming/BlockParameterName:
  Enabled: false